version: "3.9"

services:
  base: &base
    build: .
    image: safemed-streamlit-app
    networks:
      - safemed-network

  streamlit:
    <<: *base
    container_name: safemed_streamlit_app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - 8501:8501
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  safemed-network:
