model:
  best_model: DecisionTree
  f1_score: 0.7140020655267613
  feature_sets:
    features:
    - age
    - sex
    - country
    - reaction
    - drug
    - age_group
  name: reaction_outcome_classifier
  parameters:
    ccp_alpha: 0.0
    class_weight: null
    criterion: gini
    max_depth: 20
    max_features: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    monotonic_cst: null
    random_state: null
    splitter: best
  precision: 0.725870862938831
  recall: 0.7326520264717533
  target_variable: reaction_outcome
